services:
  django_gunicorn:
    build:
      context: ./django_project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
    env_file:
      - ./django_project/.env


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - django_gunicorn

volumes:
  static:
