services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: backend_service
    command: uvicorn src.sapi:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app 
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx_service
    ports:
      - "80:80"
      - "443:443" 
    depends_on:
      - backend
    restart: always
    env_file:
      - .env 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mounting SSL certificates and configs
