# Use the latest Alpine-based NGINX image or a specific version
FROM nginx:alpine

# Copy your custom configuration file into the NGINX configuration directory
COPY ./default.conf /etc/nginx/conf.d/default.conf
